Expanding integration docs
Cymmetria/honeycomb pull request #15
Opened 2018-05-26 10:20 UTC by omercnet

Added a lot of clarity on how to build an integration, we should follow up with a proper guide like we have for services.

Also fixed a bug where alert data was not returned at all if the integration required specific fields to be present.

2018-05-28 20:09 UTC, Sleeptime17 requested changes
I assume the documentation removed is due to a good reason (it's not helpful?)

2018-05-28 20:09 UTC, Sleeptime17 commented on honeycomb/integrationmanager/integration_utils.py
> +        """Use :func:`__init__` to set up any prerequisits needed before sending events, validate paramaters, etc.
prerequisites

2018-05-28 20:09 UTC, Sleeptime17 commented on honeycomb/integrationmanager/integration_utils.py
> +        :return: A tuple where the first value is a dictionary with information to display in the UI, and second is and
and [the] second is an[-d] optional file to be atta[c]hed.

2018-05-29 01:51 UTC, omercnet commented
You mean the validators? The code itself was removed a while ago I forgot to remove the autodocs

2018-05-29 10:09 UTC, omercnet commented
@Sleeptime17 please review

2018-05-29 13:24 UTC, Sleeptime17 approved these changes

2018-05-29 15:51 UTC, merged